name: 'Setup Java 21'
description: 'Setup Java 21 with Maven caching and required module options for Samstraumr'
author: 'Samstraumr Team'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Set Java module options
      shell: bash
      run: |
        # Detect Java version
        JAVA_VERSION=$("$JAVA_HOME/bin/java" -version 2>&1 | awk -F[\"\ ] '/version/ {print $3}' | tr -d '"' | cut -d. -f1)
        echo "Detected Java version: $JAVA_VERSION"
        
        # Set --add-opens flags only for Java 17+
        if [ "$JAVA_VERSION" -ge 17 ]; then
          echo "Setting --add-opens flags for Java $JAVA_VERSION"
          echo "JAVA_OPTS=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED" >> $GITHUB_ENV
          echo "JAVA_TOOL_OPTIONS=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED" >> $GITHUB_ENV
        else
          echo "Java version $JAVA_VERSION does not require --add-opens flags"
        fi
        
        # Always set Maven options
        echo "MAVEN_OPTS=-Xmx3072m" >> $GITHUB_ENV
        echo "MAVEN_CLI_OPTS=--batch-mode --errors --fail-at-end --show-version" >> $GITHUB_ENV
    
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/org/samstraumr
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Display environment
      shell: bash
      run: |
        echo "Java version:"
        java -version
        echo ""
        echo "Maven version:"
        mvn -version
