name: 'Setup Test Environment'
description: 'Common setup steps for test jobs (checkout, cache, compile)'
inputs:
  java-version:
    description: 'Java version to use'
    required: false
    default: '21'
  compile:
    description: 'Whether to compile the project'
    required: false
    default: 'false'
  test-compile:
    description: 'Whether to compile test classes'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: /root/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-

    - name: Compile project
      if: inputs.compile == 'true'
      shell: sh
      run: mvn ${{ env.MAVEN_CLI_OPTS }} clean compile

    - name: Compile test classes
      if: inputs.test-compile == 'true'
      shell: sh
      run: mvn ${{ env.MAVEN_CLI_OPTS }} test-compile
