name: 'Upload Test Results'
description: 'Upload test results and coverage reports with standardized naming'
author: 'Samstraumr Team'

inputs:
  test-type:
    description: 'Type of test (unit, component, composite, integration)'
    required: true
  retention-days:
    description: 'Number of days to retain artifacts'
    required: false
    default: '14'

runs:
  using: 'composite'
  steps:
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.test-type }}-test-results
        path: |
          **/target/surefire-reports/
          **/target/failsafe-reports/
        retention-days: ${{ inputs.retention-days }}
        if-no-files-found: warn
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.test-type }}-coverage-results
        path: |
          **/target/site/jacoco/
          **/target/jacoco.exec
        retention-days: ${{ inputs.retention-days }}
        if-no-files-found: ignore
    
    - name: Publish test results
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: ${{ inputs.test-type }} Test Results
        path: '**/target/surefire-reports/TEST-*.xml,**/target/failsafe-reports/TEST-*.xml'
        reporter: java-junit
        fail-on-error: false
